USE [master]
GO

/****** Object:  Database [MusicWebsite]    Script Date: 5/28/2017 4:00:10 PM ******/
CREATE DATABASE [MusicWebsite]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MusicWebsite', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\MusicWebsite.mdf' , SIZE = 3264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'MusicWebsite_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\MusicWebsite_log.ldf' , SIZE = 816KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [MusicWebsite] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MusicWebsite].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MusicWebsite] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MusicWebsite] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MusicWebsite] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MusicWebsite] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MusicWebsite] SET ARITHABORT OFF 
GO

ALTER DATABASE [MusicWebsite] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MusicWebsite] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MusicWebsite] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MusicWebsite] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MusicWebsite] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MusicWebsite] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MusicWebsite] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MusicWebsite] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MusicWebsite] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MusicWebsite] SET  ENABLE_BROKER 
GO

ALTER DATABASE [MusicWebsite] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MusicWebsite] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MusicWebsite] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MusicWebsite] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MusicWebsite] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MusicWebsite] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MusicWebsite] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MusicWebsite] SET RECOVERY FULL 
GO

ALTER DATABASE [MusicWebsite] SET  MULTI_USER 
GO

ALTER DATABASE [MusicWebsite] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MusicWebsite] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MusicWebsite] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MusicWebsite] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [MusicWebsite] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MusicWebsite] SET  READ_WRITE 
GO

